# Internal Coding Courses {#ICC}

MoJ analysts are recommended to take the internal training courses as they are run using the MoJ Analytical Platform and focus on topics of relevance to MoJ analysts. 

The main introductory R, SQL and Git/GitHub sessions are usually run live in February/March, June/July and October/November each year while you can also work through R, SQL, Git/GitHub and Python sessions yourself using the training material and/or recordings. 

There's also an Introduction to the Analytical Platform - see the [Analytical Platform chapter](#AP) for more information.   

## R Training

The following sessions are available; click on the links to view the latest recordings and GitHub repositories (which to view you'll need to have a GitHub account - see the [Analytical Platform User Guidance section on creating a GitHub account](https://user-guidance.analytical-platform.service.justice.gov.uk/get-started.html#3-create-github-account) to set one up) respectively. The first three are particularly recommended for new starters.

* Introduction to using R on the Analytical Platform: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQCDI_U4HsBlTKBjdR1ecVIuAaP7SlS2glsUeKnBEKPBu8E?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=Q12msS) and [Link to GitHub repository](https://github.com/moj-analytical-services/intro_using_r_on_ap)
* Introduction to R: [Link to recording of part 1](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQDCcj-3d43QSJRD07oyIIORAStW1z1GWdtIJnQGawYQBRo?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=QPN6ow), [Link to recording of part 2](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQDubY44fRDgToVCB9R5lAbKATDgHRFlV-d5G_49Rbh8DDE?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=7PlPTB) and [Link to GitHub repository](https://github.com/moj-analytical-services/IntroRTraining)
* R Charting: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQDu0VIXbId9SpDyYjqPhr8MAciAUofNzoD2cexmCQo68zo?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=5mucZl) and [Link to GitHub repository](https://github.com/moj-analytical-services/ggplotTraining)
* Introduction to R +: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EeeduKFUm2VCgnoe5mtVasABFaZjv0YDfNDm_UmxqsPDhQ?e=U7TbgO&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D) and [Link to GitHub repository](https://github.com/moj-analytical-services/intro_r_training_extension)
*	R Markdown: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EZ8leTMa301IgaE5ErPEe_gBoYiJyrj7SdSG0Dl87TiTQQ?e=Yx1iga&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D) and [Link to GitHub repository](https://github.com/moj-analytical-services/rmarkdown_training)
*	Interfacing Excel with R: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EesiimYvyj1Ml3xuoHDTi8sBjOT4VpR4r0gHULjeqMw7PQ?e=jclmy9&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D) and [Link to GitHub repository](https://github.com/moj-analytical-services/r-excel-training)
*	Writing Functions in R: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/ETjh_eHuGH1Av4IZBSRyQ_sB4Tmt7ww_PV6FgpvxHCIUoA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=k7FFfJ) and [Link to GitHub repository](https://github.com/moj-analytical-services/writing_functions_in_r)
*	Developing R packages: [Link to recording of part 1](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQDpgEdwDOF8Rp-4y2W6ykWpASW3tApCKVh5xBNKYIeQM4I?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=RWT32f), [Link to recording of part 2](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQCrhrgRyiE9QqC6H0B8ywR3AVDuHsP67KaFfbJhL8zJ-5Y?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=uTsDth) and [Link to GitHub repository](https://github.com/moj-analytical-services/rpackage_training)
*	Coding testing in R: [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EQlJD_XPK15OqLWbcgLeQv8Bok1lHAxccnYb_xYN1x5KFA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=o7qApR) and [Link to GitHub repository](https://github.com/moj-analytical-services/codetestingtraining)

You can view these and other less recent recordings (for instance of the old Developing R packages and RAP ways of working: [Link to recording of part 1](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EVLraPPmYUNMl_OHUE8OLYoBKx0oNkRhM-W1Z9uXHlQIuw?e=HiDg79&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D) and [Link to recording of part 2](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EQaKrVcb1q9ElYSGYpZRpbgBsnyXs-SPywz2wpVi41k62Q?e=badkcs&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D)) in [the R/SQL/Git Training Video Library](https://justiceuk.sharepoint.com/:u:/s/RTrainingGroup/EQmizR4ln25Hotr46oEK5_EBEzsyuy5PjQ7x0KEM_my-Qg?e=LUl8bw).

## Git/GitHub Training

Whether seeking to use R, SQL or Python, it is recommended that all newcomers attend or work through themselves the Introduction to Git/GitHub; see the [Link to GitHub repository](https://github.com/moj-analytical-services/intro_to_github_training) and most recent [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/EZONfsfWvEVGmDIB_1UKr-QB-J21PnLMRuWGC96CIRMZ-g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=KuRJfa). You may also want to watch the Intro to Git/GitHub - Merge conflict resolution: see [Link to recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/Eal0DSr7iKxFiZtSiS0tpTYBaXvrItHzKtYjGogR5Hd7eQ?e=BYjSen&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1QbGF5bGlzdCIsInJlZmVycmFsTW9kZSI6Im1pcyIsInJlZmVycmFsVmlldyI6InZpZGVvYWN0aW9ucy1zaGFyZSIsInJlZmVycmFsUGxheWJhY2tTZXNzaW9uSWQiOiI1MThkYWVmZC1kNjg5LTRiODQtOWVhNC1kY2IwYmM5MWYzYmEifX0%3D). You can view this and other less recent recordings in [the R/SQL/Git Training Video Library](https://justiceuk.sharepoint.com/:u:/s/RTrainingGroup/EQmizR4ln25Hotr46oEK5_EBEzsyuy5PjQ7x0KEM_my-Qg?e=LUl8bw).

## SQL Training

New SQL users should attend or independently complete the Introduction to SQL course. The course material is available at the [Link to Introduction to SQL GitHub repository](https://github.com/moj-analytical-services/sql_training) and the most recent [Link to Introduction to SQL Part 1 recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQA6yB1jGFiqSoJBy0psiM6kAfiJmuWlI6r45kePypbzV1E?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=ilWDn9) and [Link to Introduction to SQL Part 2 recording](https://justiceuk.sharepoint.com/:v:/s/RTrainingGroup/IQCuenvxZW2ETbHh9RpmtkW7AXOpleRtSdgGn82NSMtJZNM?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D&e=7rK09Q). You can view this and other less recent recordings in [the R/SQL/Git Training Video Library](https://justiceuk.sharepoint.com/:u:/s/RTrainingGroup/EQmizR4ln25Hotr46oEK5_EBEzsyuy5PjQ7x0KEM_my-Qg?e=LUl8bw).

## Python Training

These have not yet been run as live sessions, but you can work through the material at your own pace.

* [Introduction to Python](https://github.com/moj-analytical-services/intro-to-python)
* [Iterables in Python](https://github.com/moj-analytical-services/python-training-iterables)
* [Unit Testing and GitHub Actions](https://github.com/moj-analytical-services/actions-workshop)
* [AWS Tooling demos](https://github.com/moj-analytical-services/mojap-aws-tools-demo)
* [Pyspark in AP](https://github.com/moj-analytical-services/pyspark-in-AP-guidance)
* [Prisoid Academy - Python Training](https://github.com/moj-analytical-services/Prisoid-Academy/tree/main/Python) (if you have access to NOMIS)
* [Plotly Dash Coffee and Coding Session](https://github.com/moj-analytical-services/Coffee-and-Coding/tree/master/2020-04-14%20Python%20webapps%20using%20Plotly%20Dash)

## Get involved!

One great way of learning is by teaching. If you would be interested in playing an active role, whether delivering, updating or designing training, or co-ordinating the courses, please contact Aidan Mews (R), Georgina Eaton or Craig Medhurst (SQL), or Mike Ratford (Python).

If you have any questions please contact Aidan Mews, Georgina Eaton, Craig Medhurst or Mike Ratford.
