# Coffee and Coding {#CC}

## About Coffee and Coding

The aim of the MoJ Coffee and Coding presentations is to nurture, enable and encourage a vibrant, supportive and inclusive coding community at MoJ. Coffee & Coding provides a regular opportunity for people within MoJ who are interested in coding to:

* Share skills and knowledge
* Showcase their work and projects
* Provide advice and guidance to each other
* Network and get to know each other

Code can be shared from any language — whether R, Python, SQL, or other more specialised languages.

The format is generally 30–40 minutes for a presentation, followed by time for questions. The presentations usually take the form of a demonstration of a tool or technique and/or a show and tell of work done within the department using these methods.

## Recorded presentations

Where possible, Coffee and Coding presentations are recorded to allow people to catch up on talks they may have missed and to provide a useful training resource for colleagues.

These recordings are available on the [Coffee and Coding Sharepoint page](https://justiceuk.sharepoint.com/:u:/r/sites/MoJCoffee%26Coding/SitePages/Coffee-and-Coding-videos.aspx?csf=1&web=1&e=76lQrX). We regularly update the access list, but if you cannot access the videos please contact the Coffee and Coding mailbox.

### Some useful talks

If you are new to coding in MoJ, you might find the following recorded talks useful:-

* [Ten top tips for data presentation](https://justiceuk.sharepoint.com/:v:/r/sites/MoJCoffee%26Coding/Shared%20Documents/Coffee%20%26%20Coding/Recordings/Featured%20recordings/Coffee%20and%20Coding%20-%20Ten%20Top%20Tips%20for%20Data%20Presentation-20220511_023049.mp4?csf=1&web=1&e=ahCb6I)

* [Package management in renv](https://justiceuk.sharepoint.com/:v:/r/sites/MoJCoffee%26Coding/Shared%20Documents/Coffee%20%26%20Coding/Recordings/Featured%20recordings/Coffee%20and%20Coding%20-%20Introduction%20to%20renv%20package%20management-20220504_112130.mp4?csf=1&web=1&e=Vsi4G7)

* [Developing an Aacessible and gov.uk styled dashboard](https://justiceuk.sharepoint.com/:v:/r/sites/MoJCoffee%26Coding/Shared%20Documents/Coffee%20%26%20Coding/Recordings/Featured%20recordings/MoJ%20Coffee%20%26%20Coding%20-%20developing%20an%20accessible%20and%20gov%20uk%20styled%20dashboard%2010-08-23-20230811_094938.mov?csf=1&web=1&e=0OYR2K)

The full catalogue of recorded talks can be found [here](https://web.microsoftstream.com/channel/f6aa6c5d-e90c-44b7-8ccc-28a318fa0630).

## Code repositories

You can find code examples to go along with past Coffee and Coding presentations in our [private repo](https://github.com/moj-analytical-services/Coffee-and-Coding) (only accessible by members of the MoJ Analytical Services GitHub organisation).

## Get involved!

We are always looking for new presentations. If you have an idea for a talk you would like to give, or if you want to showcase a coding project you have been working on, please contact the [Coffee and Coding mailbox](mailto:Coffee-and-Coding@justice.gov.uk).

If you have feedback or suggestions for the Coffee and Coding team, we would love to hear from you. You can respond to our open [feedback form here](https://forms.office.com/Pages/ResponsePage.aspx?id=KEeHxuZx_kGp4S6MNndq2LJ-K_TrglJJiRCGr1CniahUNEpVWklDQUROR1g4OEE1TlZORldCWFJVTSQlQCN0PWcu).
