--- 
title: "Analytical Platform and related tools training"
author: "MoJ coding training leads (the Analytical Platform team is not responsible for the content on this page)"
date: "`r Sys.Date()`"
bibliography:
- book.bib
- packages.bib
description: This document provides information about using Analytical Platform and related tools training resources.
documentclass: book
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
---

# Summary of available resources {#summary}

## The Analytical Platform
The Analytical Platform is a data analysis environment, enabling the use of modern open source tools such as R and Python, and holding key datasets for MoJ analysts. 

To learn more about the Analytical Platform and to get up and running, go to the [Analytical Platform](#AP) chapter. More extensive information is provided by the [Analytical Platform user guidance](https://user-guidance.services.alpha.mojanalytics.xyz/#content).

## R mentoring
It is recommended that all who are new to R or Data and Analysis request an R mentor. The purpose of the scheme is to provide a better on-the-job R learning experience and raise awareness of the preferred Data and Analysis ways of working that will for instance enable people to get up to speed more quickly with others’ code. The scheme is also open to non-coders who need to use the Analytical Platform to advise them through the learning process, and for those commencing a more complex project involving the use of R. 

To request an R mentor please complete [this mentee form](https://forms.office.com/Pages/ResponsePage.aspx?id=KEeHxuZx_kGp4S6MNndq2PdkMZw8L-FEkMSL2t4Oet1UQVlWMUwzOVZRNUVKSTVZU0pPTUY0MDlZTSQlQCN0PWcu). If you could become an R mentor (we have a shortage of mentors) please complete [this mentor form](https://forms.office.com/Pages/ResponsePage.aspx?id=KEeHxuZx_kGp4S6MNndq2PdkMZw8L-FEkMSL2t4Oet1UNUw1N1M0NVNQSTNOVkdHOUtMQ1lMT0lHTSQlQCN0PWcu). For more information please contact Jessica Dawson.

## Internal R (and SQL) Training Group materials
The live R, SQL and GitHub training sessions are generally run twice or three times each year. However, recordings are available so you can work through yourself. These sessions are run using the MoJ Analytical Platform so they are recommended for those working in Data and Analysis (or with the Analytical Platform). You can view the material (in the Github repositories) at:

* [Introduction to R](https://github.com/moj-analytical-services/IntroRTraining)
* [R Charting](https://github.com/moj-analytical-services/ggplotTraining)
*	[Introduction to GitHub](https://github.com/moj-analytical-services/git-training-class)
*	[R Markdown](https://github.com/moj-analytical-services/rmarkdown_training)
*	[Interfacing Excel with R](https://github.com/moj-analytical-services/r-excel-training)
*	[Writing Functions in R](https://github.com/moj-analytical-services/writing_functions_in_r)
*	[Developing R packages & RAP ways of working](https://github.com/moj-analytical-services/rpackage_training)
*	[Introduction to SQL](https://github.com/moj-analytical-services/sql_training)

The recordings of the R and SQL training sessions (the Introduction to GitHub session has not yet been recorded) are stored on MS Stream in the links below:

* [R training MS Stream Channel](https://web.microsoftstream.com/channel/aa3cda5d-99d6-4e9d-ac5e-6548dd55f52a)
*	[SQL training MS Stream Channel](https://web.microsoftstream.com/channel/7cd1cdaf-79cb-4e1e-ab2b-448d8f69f6a1)

One great way of learning is by teaching. If you would be interested in being part of the R (and SQL) training group, whether booking courses/allocating places, designing training, or presenting, please contact Aidan Mews or Georgina Eaton. 

If you have any questions please contact Aidan Mews or Georgina Eaton.

## Coffee and Coding and Bitesize sessions
The internal R/SQL/Github training (see above) is complemented by [coffee and coding](https://web.microsoftstream.com/channel/f6aa6c5d-e90c-44b7-8ccc-28a318fa0630) and [bitesize](https://web.microsoftstream.com/channel/5a6012a2-efd6-4b86-902d-98c864427caa) sessions. The contacts are Katharine Breeze and George Papadopoulos respectively.

## Analytical Function training opportunities
There are now many technical Analytical Function training opportunities for analysts including about topics not presently covered internally e.g. an introduction to python. Examples useful for RAP practitioners include [Best practice in programming – clean code – GSS (civilservice.gov.uk)](https://gss.civilservice.gov.uk/training/best-practice-in-programming-clean-code/) and an [Introduction to unit testing – GSS (civilservice.gov.uk)](Introduction to unit testing – GSS (civilservice.gov.uk)). You can view such opportunities via:

*	[A user-friendly list (but not updated since Jan 2021)](https://www.gov.uk/guidance/af-learning-curriculum-technical)
*	[GSS Training Courses (many which are open to all analysts)](https://gss.civilservice.gov.uk/training-courses/)

## Datacamp
Paid Datacamp licenses are beneficial to cover gaps in current training provision that are not picked up by either internal or GSS/Analytical function training currently e.g. more advanced R, SQL, and python skills. You can read more about Datacamp [here](https://www.datacamp.com/). 

If you would like to have a Datacamp license please contact Aidan Mews or Rosina Costello providing a brief explanation about why it will be important for your work along with approval from your deputy director.

## Other assistance
Technical help can be requested via the following [Data and Analysis slack channels](https://asdslack.slack.com/): 

* intro_R which provides support to those starting out in the world of R and RAP.
*	R which is for beginners and experts alike.
*	sql
*	python

You may also find useful a trello board providing [Links to further free online analytical training including in R](https://trello.com/b/D5pSkqnT/online-analytical-training) and [R cheatsheets](https://rstudio.com/resources/cheatsheets/).

# Analytical Platform {#AP}

## Introduction
To gain an overview of the Analytical Platform watch this 2-3 min [introductory video](https://www.youtube.com/watch?v=5467Hl3X9EI&t=95s). For more technical details, you can also read the user guidance section [About the Analytical Platform](https://user-guidance.services.alpha.mojanalytics.xyz/about.html#about-the-analytical-platform).

## Summary of key terms
It will help you to be familiar with the following key terms:

- **Analytical Platform (AP)**: A data analysis environment providing modern tools and key datasets for MoJ analysts. AP contains training documents, resources, and access to various analytical software such as Rstudio and Jupyter.
- **Control Panel**: A place to navigate to Rstudio, Jupyter, S3 Buckets etc
- **RStudio**: Development environment for writing R code and R Shiny apps
- **JupyterLab**: Development environment for writing Python code including Python notebooks
- **Git**: Version control software that enables multiple people to make separate changes at the same time.
- **GitHub**: A web-based interface that uses Git and on which you publish and share your version-controlled code. You use Git locally (e.g. using RStudio) to track versions of your code, and then submit those changes to Github. 
- **GitHub Repositories (Repo)**: Similar to setting up a project folder on DOM1 shared drive to save work and share with others. Files on Github Repos represent the definitive version of the project. Everyone who works on the project makes contributions from their own personal versions.
- **Amazon S3**: A web-based cloud storage platform. Where your home directory stores working copies of code, data and final analytical outputs should be stored in Amazon S3. Access to amazon S3 buckets can be managed. 
- **Slack**: Collaboration tool where you can get technical support for Analytical Platform tools such as R, Python, Git. You can share knowledge, submit admin requests and communicate quickly with other AP users.

## Getting set up
First, so that you can request any help you need when getting set up on the Analytical Platform, it is recommended that you join the [Data and Analysis Slack](https://app.slack.com/client/T1PU1AP6D/C4PF7QAJZ). You can read a very brief overview [here](#other-assistance) with further information including how to sign-up [here](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html#3-slack-account).

Second, follow the steps in the [Getting Started section of the Analytical Platform User Guide](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html#get-started). You need to:

- Set up a [GitHub account with two-factor authentication](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html#1-github-account).   
- Set up a [Analytical Platform account](https://user-guidance.services.alpha.mojanalytics.xyz/get-started.html#2-analytical-platform-account).  

Once you have completed the above two steps, you should be able to access the [Analytical Platform Control Panel](https://controlpanel.services.alpha.mojanalytics.xyz/tools/) and from there open the relevant tool (e.g. RStudio for R). 

Lastly, as code written on the Analytical Platform should be stored in a Git repository on GitHub, complete the steps [to configure Git and GitHub for the Analytical Platform](https://user-guidance.services.alpha.mojanalytics.xyz/github.html#setup-github-keys-to-access-it-from-r-studio-and-jupyter). You can learn more about GitHub by viewing [this introduction](https://digital.gov/resources/an-introduction-github/) and by attending [the internal introduction to GitHub](https://moj-analytical-services.github.io/ap-tools-training/index.html#internal-r-and-sql-training-group-materials)

## Managing data
Once you have got set up on the Analytical Platform, do read about the following data management/handling topics:

- [How data are held on the Analytical Platform and finding the data you need](https://user-guidance.services.alpha.mojanalytics.xyz/data/#dropShadow). You can read about the three different data storage options (Amazon S3, Curated databases and home directories). 
- Working with [Amazon S3](https://user-guidance.services.alpha.mojanalytics.xyz/data/amazon-s3/#amazon-s3), including how to [upload data files](https://user-guidance.services.alpha.mojanalytics.xyz/data/amazon-s3/#upload-files-to-amazon-s3) and [download data files](https://user-guidance.services.alpha.mojanalytics.xyz/data/amazon-s3/#download-or-read-files-from-amazon-s3) using Amazon S3.
- [Information governance procedures](https://user-guidance.services.alpha.mojanalytics.xyz/information-governance.html#content) to be followed, in particular when moving any data onto the Analytical Platform, when a [data movement form](https://user-guidance.services.alpha.mojanalytics.xyz/information-governance.html#data-movement-form) must be completed.
- Data [retention policies](https://user-guidance.services.alpha.mojanalytics.xyz/information-governance.html#data-retention) including when deleting data means they are permanently deleted. 

